// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
export function getLabelTranslations(key: string) {
  return {
    en: translations.en.logcica.fields[key] ?? key,
    fr: translations.fr.logcica.fields[key] ?? key,
  }
}

export function getPlaceholderTranslations(key: string) {
  return {
    en: translations.en.logcica.placeholder[key] ?? key + ' placeholder',
    fr: translations.fr.logcica.placeholder[key] ?? key + ' placeholder',
  }
}

// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
export function getCollectionLabelsTranslations(collectionSlug: string) {
  return {
    singular: {
      en: translations.en.logcica.collections[collectionSlug + '_one'] ?? collectionSlug,
      fr: translations.fr.logcica.collections[collectionSlug + '_one'] ?? collectionSlug,
    },
    plural: {
      en: translations.en.logcica.collections[collectionSlug + '_other'] ?? collectionSlug,
      fr: translations.fr.logcica.collections[collectionSlug + '_other'] ?? collectionSlug,
    },
  }
}

// this follows i18next structure
const translations = {
  en: {
    logcica: {
      placeholder: {
        recipeYieldStatement: 'For 4 persons',
      },
      fields: {
        name: 'Name',
        area: 'Area',
        categories: 'Categories',
        ingredientList: 'Ingredients',
        quantity: 'Quantity',
        unit: 'Unit',
        value: 'Value',
        description: 'Description',
        short: 'Short',
        author: 'Author',
        stepStatement: 'Steps',
        cookTime: 'Cook time',
        prepTime: 'Preparation time',
        totalTime: 'Total time',
        difficulty: 'Difficulty',
        seasonality: 'Seasonality',
        yieldStatement: 'Yield',
        costCategory: 'Cost',
        nutrientList: 'Nutrients',
        mainImage: 'Main image',
        images: 'Images',
        nutrient: 'Nutrient',
        partnerships: 'Partnership',
        organisations: 'Organisation',
        persons: 'Person',
        number: 'number',
        legalFormShort: 'legalFormShort',
        legalForm: 'legalForm',
        registeredAt: 'registeredAt',
        workspaces: 'workspaces',
        workspace: 'workspace',
        url: 'url',
        place: 'place',
        mainActivity: 'mainActivity',
        owner: 'owner',
        contacts: 'contacts',
        profiles: 'profiles',
        givenName: 'givenName',
        familyName: 'familyName',
        internalName: 'internalName',
        manager: 'manager',
        activities: 'activities',
        isMain: 'isMain',
        productionCategories: 'productionCategories',
        otherCategories: 'otherCategories',
        mainWorkspace: 'mainWorkspace',
        type: 'type',
        marketplace: 'marketplace',
        catalog: 'catalog',
        availabilities: 'availabilities',
        link: 'link',
        key: 'key',
        address: 'address',
        locality: 'locality',
        municipality: 'municipality',
        region: 'region',
        country: 'country',
        within: 'within',
        title: 'title',
        street: 'street',
        postalCode: 'postalCode',
        gmaps: 'gmaps',
        id: 'id',
        center: 'center',
      },
      collections: {
        recipes_one: 'Recipe',
        recipes_other: 'Recipes',
        persons_one: 'Person',
        persons_other: 'Persons',
        organisations_one: 'Organisation',
        organisations_other: 'Organisations',
        partnerships_one: 'Partnership',
        partnerships_other: 'Partnerships',
        workspaces_one: 'Workspace',
        workspaces_other: 'Workspaces',
        activities_one: 'Activity',
        activities_other: 'Activities',
        counters_one: 'Counter',
        counters_other: 'Counters',
        places_one: 'Place',
        places_other: 'Places',
      },
    },
  },
  fr: {
    logcica: {
      placeholder: {
        recipeYieldStatement: 'Pour 4 personnes',
      },
      fields: {
        name: 'Nom',
        area: 'Territoire',
        categories: 'Catégories',
        ingredientList: 'Ingrédients',
        quantity: 'Quantité',
        unit: 'Unité',
        value: 'Valeur',
        description: 'Description',
        short: 'Court',
        author: 'Auteur',
        stepStatement: 'Instructions',
        cookTime: 'Temps de cuisson',
        prepTime: 'Temps de préparation',
        totalTime: 'Temps total',
        difficulty: 'Difficulté',
        seasonality: 'Saisonnalité',
        yieldStatement: 'Rendement',
        costCategory: 'Coût',
        nutrientList: 'Valeurs nutritionnelles',
        mainImage: 'Image principale',
        images: 'Images',
        nutrient: 'Nutriment',
        partnerships: 'Partenariat',
        organisations: 'Organisation',
        persons: 'Personne',
        number: 'Nombre',
        legalFormShort: 'Forme juridique Abrégée',
        legalForm: 'Forme juridique',
        registeredAt: 'Inscrit à',
        workspaces: 'Espaces de travail',
        workspace: 'Espace de travail',
        url: 'url',
        place: 'Lieu',
        mainActivity: 'Activité principale',
        owner: 'Propriétaire',
        contacts: 'Contacts',
        profiles: 'Profils',
        givenName: 'Prénom',
        familyName: 'Nom de famille',
        internalName: 'Nom interne',
        manager: 'Directeur',
        activities: 'Activités',
        isMain: 'Principal',
        productionCategories: 'Catégories de production',
        otherCategories: 'Autres catégories',
        mainWorkspace: 'Espace de travail principal',
        type: 'Type',
        marketplace: 'Marché',
        catalog: 'Catalogue',
        availabilities: 'Disponibilités',
        link: 'Lien',
        key: 'Clé',
        address: 'Adresse',
        locality: 'Localité',
        municipality: 'Municipalité',
        region: 'Région',
        country: 'Pays',
        within: 'Compris dans',
        title: 'Titre',
        street: 'Rue',
        postalCode: 'Code Postal',
        gmaps: 'Google maps',
        id: 'id',
        center: 'Centre',
      },
      collections: {
        recipes_one: 'Recette',
        recipes_other: 'Recettes',
        persons_one: 'Personne',
        persons_other: 'Personnes',
        organisations_one: 'Organisation',
        organisations_other: 'Organisations',
        partnerships_one: 'Partenariat',
        partnerships_other: 'Partenariats',
        workspaces_one: 'Espace de travail',
        workspaces_other: 'Espaces de travail',
        activities_one: 'Activité',
        activities_other: 'Activités',
        counters_one: 'Comptoir',
        counters_other: 'Comptoirs',
        places_one: 'Emplacement',
        places_other: 'Emplacements',
      },
    },
  },
}
